Update develop.yml

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -1,8 +1,10 @@
-name: CD with Gradle
+name: CICD
 
 on:
+  push:
+    branches: [ "main" ]
   pull_request:
-    types: [ closed ]
+    branches: [ "main" ]
 
 permissions:
   contents: read
@@ -10,47 +12,97 @@ permissions:
 jobs:
   build:
     runs-on: ubuntu-latest
-
     steps:
       - uses: actions/checkout@v3
-
-      - name: Set up JDK 17
+      - name: Install JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
-          distribution: "adopt"
+          distribution: 'temurin'
 
-      - name: Make application.yml
-        run: |
-          cd ./src/main
-          mkdir resources
-          cd resources
-          touch ./application.yml
-          echo "${{ secrets.YML }}" > ./application.yml
-        shell: bash
+      - name: Make application-secret.yml
+        run : |
+          echo ${{ secrets.APPLICATION_SECRET }} | base64 --decode > ./src/main/resources/application-secret.yml
 
       - name: Build with Gradle
         run: |
           chmod +x ./gradlew
-          ./gradlew clean build -x test
+          ./gradlew clean build 
 
-      - name: Docker build & push to docker repo
-        run: |
-          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
-          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/storyteller .
-          docker push ${{ secrets.DOCKER_REPO }}/storyteller
-
-      - name: Deploy to server
-        uses: appleboy/ssh-action@master
-        id: deploy
+      - name: Login to DockerHub
+        uses: docker/login-action@v1
         with:
-          host: ${{ secrets.HOST }}
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Build Docker
+        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/storyteller .
+        
+      - name: Push Docker
+        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/storyteller:latest
+        
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set target IP
+        run: |
+          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.STORYTELLER_IP }}/env")
+          echo $STATUS
+          if [ $STATUS = 200 ]; then
+            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.STORYTELLER_IP }}/env")
+          else
+            CURRENT_UPSTREAM=green
+          fi
+          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
+          if [ $CURRENT_UPSTREAM = blue ]; then
+            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+          elif [ $CURRENT_UPSTREAM = green ]; then
+            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+          else
+            echo "error"
+            exit 1
+          fi
+          
+      - name: Docker compose
+        uses: appleboy/ssh-action@master
+        with:
           username: ubuntu
-          key: ${{ secrets.KEY }}
-          envs: GITHUB_SHA
+          host: ${{ secrets.STORYTELLER_IP }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
           script: |
-            sudo docker rm -f $(docker ps -qa)
-            sudo docker stop $(docker ps -a -q)
-            sudo docker pull ${{ secrets.DOCKER_REPO }}/storyteller
-            sudo docker-compose up --build -d
-            sudo docker image prune -f
+            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/storyteller:latest
+            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d
+      
+      - name: Check deploy server URL
+        uses: jtalk/url-health-check-action@v3
+        with:
+          url: http://${{ secrets.STORYTELLER_IP }}:${{env.STOPPED_PORT}}/env
+          max-attempts: 3
+          retry-delay: 10s
+
+      - name: Change nginx upstream
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.STORYTELLER_IP }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
+          script: |
+            sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 
+
+      - name: Stop current server
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.STORYTELLER_IP }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
+          script: |
+            sudo docker stop ${{env.CURRENT_UPSTREAM}}
+            sudo docker rm ${{env.CURRENT_UPSTREAM}}
